export const deliveryItems =[
    {
        id:1,
        title:'Pizza',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQkIUSaMlAqbJQgFrjpZ9gHUzET19aPMcGy0w&usqp=CAU'
    },
    {
        id:2,
        title:'Burger',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRDMehMoc57kchtpkCfog-3espJPbm5QbL6Qg&usqp=CAU'
    },
    {
        id:3,
        title:'Rolls',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQg5s8LdSCv9Cj9wGmsfx6dN3bRbVvLFCrFuw&usqp=CAU'
    },
    {
        id:4,
        title:'Biryani',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTXLIug_SuNejptRT0TpeyzBFrZsjZoliOxaQ&usqp=CAU'
    },
    {
        id:5,
        title:'Drinks',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ8zAr6kt9B6bvxpPI3PX9A4dWlQsWfLLPyGw&usqp=CAU'
    },
    {
        id:6,
        title:'Chicken Curry',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRTz0iuyY1s0pgmkmhIqCvc2ajvxINCQw1EnA&usqp=CAU'
    },
    {
        id:7,
        title:'Paneer',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQcQOZnoMOFa2v6tfAzt1l-QE9selu8QRvEkA&usqp=CAU'
    },
    {
        id:8,
        title:'Egg Curry',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRpFeKbBY1yLrv9FQ4groQaJ70zn7yLQOZsdw&usqp=CAU'
    },
    {
        id:9,
        title:'Cake',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR6i57i9NEXd4pe8JwL0nmaMD7kTT0e-oZ51A&usqp=CAU'
    },
    {
        id:10,
        title:'Chaat',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRokAX_t-JlVHrjM8LCOOfUlVjvLul0H7_kdA&usqp=CAU'
    },
    {
        id:11,
        title:'Momos',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTlZKMIZn8YRI9wFMTWWqARAx8egpcg-BQ-7g&usqp=CAU'
    },
    {
        id:12,
        title:'Chinies',
        img:'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRcd92pfMdS8AG_yALc9G5GSwVB3ipqh23LWg&usqp=CAU'
    }
]